collections:

  stone:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "stone"
    values:
      layout: "flickity"
  - scope:
      path: ""
    values:
      layout: "default"